import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';

test('kb docs describe the staged public package set and current consumer entry point', () => {
  const repoReadme = readFileSync(path.resolve(process.cwd(), 'README.md'), 'utf8');
  assert.match(repoReadme, /## Public Package Set/);
  assert.match(repoReadme, /@emmassist-co\/kb-core/);
  assert.match(repoReadme, /@emmassist-co\/kb-storage-file/);
  assert.match(repoReadme, /@emmassist-co\/kb-storage-cloudflare/);
  assert.match(repoReadme, /@emmassist-co\/kb-http/);
  assert.match(repoReadme, /@emmassist-co\/kb-mcp/);
  assert.match(repoReadme, /@emmassist-co\/kb-dashboard/);
  assert.match(repoReadme, /@emmassist-co\/kb-cli/);
  assert.match(repoReadme, /Not yet in the staged public package set/);
  assert.match(repoReadme, /@emmassist-co\/kb-flue-adapter/);
  assert.match(repoReadme, /@emmassist-co\/kb-autoresearch/);
  assert.match(repoReadme, /## Should An Agent Use KB\?/);
  assert.match(repoReadme, /durable, inspectable workspace memory shared by a human and multiple agents/);
  assert.match(repoReadme, /### Trust Model/);
  assert.match(repoReadme, /Evidence-first writes/);
  assert.match(repoReadme, /Human correction path/);
  assert.match(repoReadme, /### Human \+ Multi-Agent Workflow/);
  assert.match(repoReadme, /Codex records a structured entity update/);
  assert.match(repoReadme, /Claude Code later searches/);
  assert.match(repoReadme, /### Agent Operating Protocol/);
  assert.match(repoReadme, /Search KB before answering factual questions/);
  assert.match(repoReadme, /Use `relate` for explicit edges/);
  assert.match(repoReadme, /docs\/architecture\/kb-storage-adapters\.md/);
  assert.match(repoReadme, /docs\/product\/kb-agent-improvement-support\.md/);
  assert.match(repoReadme, /agents think; KB stores, validates, retrieves, relates, and exposes evidence/);
  assert.match(repoReadme, /## Agent-First Architecture Map/);
  assert.match(repoReadme, /One durable truth surface/);
  assert.match(repoReadme, /One contract, many transports/);
  assert.match(repoReadme, /Cloudflare is production, local is support/);
  assert.match(repoReadme, /Plain agents stay plain/);
  assert.match(repoReadme, /Codex \/ Claude \/ Pi \/ Cursor \/ scripts/);
  assert.match(repoReadme, /kb CLI/);
  assert.match(repoReadme, /kb-local` remains a backward-compatible alias/);
  assert.match(repoReadme, /kb-agent-improvement/);
  assert.match(repoReadme, /kb-http \/v1/);
  assert.match(repoReadme, /kb-mcp \/mcp/);
  assert.match(repoReadme, /Cloudflare Durable Object/);
  assert.match(repoReadme, /Cloudflare R2/);
  assert.match(repoReadme, /does \*\*not\*\* claim to own every chat bridge or agent runtime/);
  assert.match(repoReadme, /## Setup And Lifecycle Paths/);
  assert.match(repoReadme, /Local browser dashboard/);
  assert.match(repoReadme, /npx kb dashboard --port 3001/);
  assert.match(repoReadme, /CLI-only installs can omit the dashboard package/);
  assert.match(repoReadme, /without Obsidian/);
  assert.match(repoReadme, /Local-to-remote migration is intentionally boring/);
  assert.match(repoReadme, /## Multi-Writer And Recovery Boundaries/);
  assert.match(repoReadme, /replaceLinksForOrigin|replaced by origin/);
  assert.doesNotMatch(repoReadme, /\btenant\b/i);
  assert.match(repoReadme, /## Benchmark Standard/);
  assert.match(repoReadme, /admin-world-v3/);
  assert.match(repoReadme, /gbrain-evals-upstream/);
  assert.match(repoReadme, /gbrain-world/);
  assert.match(repoReadme, /literal upstream `gbrain-evals` harness run side-by-side against real `gbrain` and our KB on the public `world-v1` benchmark/);
  assert.match(repoReadme, /core-six/);
  assert.match(repoReadme, /Fixed P@5/);
  assert.match(repoReadme, /Returned P@5/);
  assert.match(repoReadme, /Fixed ceiling/);
  assert.match(repoReadme, /\| `core-six` \| deterministic floor \| `72 retrieval \+ 28 non-retrieval` \| `30\.6%` \| `33\.8%` \| `31\.7%` \| `96\.5%` \| `89\.7%` \| `87\.3%` \| `pass` \|/);
  assert.match(repoReadme, /\| `admin-world-v3 dev` \| product-core optimize rail \| `216 queries` \| `40\.0%` \| `90\.3%` \| `42\.0%` \| `95\.6%` \| `98\.7%` \| `91\.4%` \| `floor reached` \|/);
  assert.match(repoReadme, /\| `admin-world-v3 holdout` \| product-core confirm rail \| `72 queries` \| `40\.6%` \| `90\.9%` \| `42\.2%` \| `96\.5%` \| `100\.0%` \| `93\.0%` \| `floor reached` \|/);
  assert.match(repoReadme, /\| `gbrain-evals-upstream` \| strict public external rail \| `145 queries` \| `n\/a` \| `76\.6%` \| `n\/a` \| `99\.5%` \| `n\/a` \| `n\/a` \| `real gbrain side-by-side` \|/);
  assert.match(repoReadme, /\| `gbrain-world` \| local diagnostic rail \| `145 queries` \| `36\.0%` \| `76\.7%` \| `36\.0%` \| `100\.0%` \| `100\.0%` \| `100\.0%` \| `diagnostic only` \|/);
  assert.match(repoReadme, /\| `relation-paraphrase-v1` \| anti-cheat paraphrase rail \| `4 queries` \| `45\.0%` \| `87\.5%` \| `45\.0%` \| `100\.0%` \| `100\.0%` \| `100\.0%` \| `guardrail pass` \|/);
  assert.match(repoReadme, /\| `relation-transfer-v1` \| prose-only transfer rail \| `4 queries` \| `20\.0%` \| `87\.5%` \| `20\.0%` \| `100\.0%` \| `100\.0%` \| `100\.0%` \| `guardrail pass` \|/);
  assert.match(repoReadme, /external reference rail/);
  assert.match(repoReadme, /relation-paraphrase-v1/);
  assert.match(repoReadme, /relation-transfer-v1/);
  assert.match(repoReadme, /check:kb:anti-cheat/);
  assert.match(repoReadme, /before describing the GBrain posture as evidence of product-general relation quality/);
  assert.match(repoReadme, /after any major KB change, rerun the benchmark rails and refresh the published benchmark snapshot/);

  const benchmarkDocs = readFileSync(path.resolve(process.cwd(), 'docs/operations/kb-benchmark.md'), 'utf8');
  assert.match(benchmarkDocs, /npm run check:kb:anti-cheat/);
  assert.match(benchmarkDocs, /npm run eval:kb:relation-paraphrase/);
  assert.match(benchmarkDocs, /npm run eval:kb:relation-transfer/);
  assert.match(benchmarkDocs, /Do not describe GBrain results as product-general relation quality unless these guardrails pass too/);
  assert.match(benchmarkDocs, /official GBrain GitHub README headline/);
  assert.match(benchmarkDocs, /same `240` page corpus, the same `145` public queries/);
  assert.match(benchmarkDocs, /Runtime\/package code is guarded against GBrain-specific markers/);

  assert.match(repoReadme, /288 retrieval queries/);
  assert.match(repoReadme, /72 holdout queries/);
  assert.match(repoReadme, /kb-scorecard-latest\.md/);
  assert.match(repoReadme, /GBrain` official GitHub README headline/);
  assert.match(repoReadme, /same upstream `gbrain-evals` runner, the same `240` page corpus, the same `145` public queries/);
  assert.match(repoReadme, /benchmark-metadata-blind/);
  assert.match(repoReadme, /not a claim that KB is broadly better than GBrain across synthesis, ingestion, vector\/reranker search, or every memory workflow/);
  assert.match(repoReadme, /gbrain returned-denominator P@5 49\.1%, R@5 97\.9%/);
  assert.match(repoReadme, /kb-upstream returned-denominator P@5 76\.6%, R@5 99\.5%/);
  assert.match(repoReadme, /optimize on `admin-world-v3 dev`/);
  assert.match(repoReadme, /confirm on `admin-world-v3 holdout`/);
  assert.match(repoReadme, /block regressions on `core-six dev` and `core-six holdout`/);
  assert.match(repoReadme, /external reference rail/);
  assert.match(repoReadme, /after any major KB change, rerun the benchmark rails and refresh the published benchmark snapshot/);

  const packageSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-write/SKILL.md'), 'utf8');
  assert.match(packageSkill, /github\.com\/emmassist-co\/kb/);

  const setupSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-local-setup/SKILL.md'), 'utf8');
  assert.doesNotMatch(setupSkill, /GITHUB_PACKAGES_TOKEN/);
  assert.match(setupSkill, /KB_ROOT_DIR/);
  assert.match(setupSkill, /KB_WORKSPACE_ID/);
  assert.match(setupSkill, /npx kb inspect/);
  assert.match(setupSkill, /node_modules\/@emmassist-co\/kb-cli\/skills\/kb-local-setup/);
  assert.ok(existsSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-local-setup/agents/openai.yaml')));

  const cloudflareSetupSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-cloudflare-setup/SKILL.md'), 'utf8');
  assert.match(cloudflareSetupSkill, /canonical Cloudflare-hosted KB surface/);
  assert.match(cloudflareSetupSkill, /canonical-production/);
  assert.match(cloudflareSetupSkill, /KB_BASE_URL/);
  assert.match(cloudflareSetupSkill, /KB_API_TOKEN/);
  assert.match(cloudflareSetupSkill, /kb cloudflare deploy/);
  assert.match(cloudflareSetupSkill, /kb cloudflare verify/);
  assert.match(cloudflareSetupSkill, /\.capabilities\.trustSubstrate/);
  assert.match(cloudflareSetupSkill, /\.data \| \{workspaceRole, trustSubstrate\}/);
  assert.match(cloudflareSetupSkill, /node_modules\/@emmassist-co\/kb-cli\/skills\/kb-cloudflare-setup/);
  assert.match(cloudflareSetupSkill, /docs\/cloudflare-agent-setup\.md/);
  assert.ok(existsSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-cloudflare-setup/agents/openai.yaml')));

  const kbCliPackage = JSON.parse(readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/package.json'), 'utf8')) as {
    bin?: Record<string, string>;
    version: string;
    files: string[];
    dependencies?: Record<string, string>;
  };
  assert.equal(kbCliPackage.bin?.kb, './bin/kb-local.mjs');
  assert.equal(kbCliPackage.bin?.['kb-local'], './bin/kb-local.mjs');
  assert.equal(kbCliPackage.dependencies?.['@emmassist-co/kb-dashboard'], undefined);

  const agentImprovementDoc = readFileSync(path.resolve(process.cwd(), 'docs/product/kb-agent-improvement-support.md'), 'utf8');
  assert.match(agentImprovementDoc, /Agents think\. KB stores, validates, retrieves, relates, and exposes evidence\./);
  assert.match(agentImprovementDoc, /Recipe run state/);
  assert.match(agentImprovementDoc, /explicit non-goal/);
  assert.match(agentImprovementDoc, /Command Resolver/);

  const readme = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/README.md'), 'utf8');
  assert.match(readme, /npm install @emmassist-co\/kb-cli --@emmassist-co:registry=https:\/\/npm\.pkg\.github\.com/);
  assert.match(readme, /npx kb inspect/);
  assert.match(readme, /`kb-local` remains a backward-compatible alias/);
  assert.match(readme, /kb-local-setup/);
  assert.match(readme, /cloudflare-agent-setup\.md/);
  assert.match(readme, /kb-cloudflare-setup/);
  assert.match(readme, /kb-agent-improvement/);
  assert.match(readme, /node_modules\/@emmassist-co\/kb-cli\/recipes/);
  assert.match(readme, /recipes\/README\.md/);
  assert.match(readme, /KB_API_TOKEN/);
  assert.match(readme, /kb cloudflare deploy/);
  assert.match(readme, /kb cloudflare verify/);
  assert.match(readme, /@emmassist-co\/kb-dashboard/);
  assert.match(readme, /kb dashboard --port 3001/);
  assert.match(readme, /CLI-only installs do not need the dashboard package/);
  assert.match(readme, /local operator surface/);
  assert.match(readme, /kb validate-mirror --changes/);
  assert.match(readme, /kb health --stats/);
  assert.match(readme, /kb conflicts list/);
  assert.match(readme, /node_modules\/@emmassist-co\/kb-cli\/skills\/kb-write/);

  assert.match(readme, /npm\.pkg\.github\.com/);

  const mcpReadme = readFileSync(path.resolve(process.cwd(), 'packages/kb-mcp/README.md'), 'utf8');
  assert.match(mcpReadme, /MCP transport adapter/);
  assert.match(mcpReadme, /Install/);
  assert.match(mcpReadme, /Tool Surface/);
  assert.match(mcpReadme, /npm run smoke:kb-mcp/);
  assert.match(mcpReadme, /shared-secret bearer auth/);
  assert.match(mcpReadme, /streamable-http/);
  assert.match(mcpReadme, /Authorization/);
  assert.match(mcpReadme, /workspace-scoped runtime/);
  assert.match(mcpReadme, /Agent Adoption Boundary/);
  assert.match(mcpReadme, /Use CLI skills for command-running agents/);
  assert.match(mcpReadme, /Use `\/mcp` for MCP-aware clients/);
  assert.match(mcpReadme, /npx kb cloudflare verify/);

  const storageGuidePath = path.resolve(process.cwd(), 'docs/architecture/kb-storage-adapters.md');
  assert.ok(existsSync(storageGuidePath));
  const storageGuide = readFileSync(storageGuidePath, 'utf8');
  assert.match(storageGuide, /KnowledgeStore/);
  assert.match(storageGuide, /FileKnowledgeStore/);
  assert.match(storageGuide, /SnapshotKnowledgeStore/);
  assert.match(storageGuide, /R2CanonicalKbStore/);
  assert.match(storageGuide, /Building An S3-Style Adapter/);
  assert.match(storageGuide, /replaceLinksForOrigin/);
  assert.match(storageGuide, /Do not duplicate or fork/);

  const fileStoreReadme = readFileSync(path.resolve(process.cwd(), 'packages/kb-storage-file/README.md'), 'utf8');
  assert.match(fileStoreReadme, /kb-storage-adapters\.md/);
  const cloudflareStoreReadme = readFileSync(path.resolve(process.cwd(), 'packages/kb-storage-cloudflare/README.md'), 'utf8');
  assert.match(cloudflareStoreReadme, /kb-storage-adapters\.md/);

  const quickstart = readFileSync(path.resolve(process.cwd(), 'docs/consumer-quickstart.md'), 'utf8');
  assert.match(quickstart, /GitHub Packages for the `@emmassist-co` scope/);
  assert.match(quickstart, /cloudflare-agent-setup\.md/);
  assert.match(quickstart, /KB_WORKSPACE_ID/);
  assert.match(quickstart, /KB_ROOT_DIR/);
  assert.match(quickstart, /npm install @emmassist-co\/kb-cli --@emmassist-co:registry=https:\/\/npm\.pkg\.github\.com/);
  assert.match(quickstart, /npx kb sync status/);
  assert.match(quickstart, /npx kb validate-mirror/);
  assert.match(quickstart, /npx kb health/);
  assert.match(quickstart, /support and debugging path/);
  assert.match(quickstart, /npx skills add \.\/node_modules\/@emmassist-co\/kb-cli\/skills\/kb-local-setup/);
  assert.match(quickstart, /npx skills add \.\/node_modules\/@emmassist-co\/kb-cli\/skills\/kb-cloudflare-setup/);
  assert.match(quickstart, /GitHub source install remains available as a fallback/);
  assert.match(quickstart, /npx skills add https:\/\/github\.com\/emmassist-co\/kb\/tree\/main\/packages\/kb-cli\/skills\/kb-local-setup/);
  assert.match(quickstart, /npx skills add https:\/\/github\.com\/emmassist-co\/kb\/tree\/main\/packages\/kb-cli\/skills\/kb-cloudflare-setup/);
  assert.match(quickstart, /kb-agent-improvement/);
  assert.match(quickstart, /node_modules\/@emmassist-co\/kb-cli\/recipes/);
  assert.match(quickstart, /canonical Cloudflare KB surface/);
  assert.match(quickstart, /KB_API_TOKEN/);
  assert.match(quickstart, /kb cloudflare deploy/);
  assert.match(quickstart, /kb cloudflare verify/);
  assert.match(quickstart, /streamable-http/);
  assert.match(quickstart, /Command-running local agent/);
  assert.match(quickstart, /MCP-aware client/);
  assert.match(quickstart, /smoke:kb-agent-readiness/);
  assert.match(quickstart, /## Agent Operating Protocol/);
  assert.match(quickstart, /search before answering workspace-specific factual questions/);
  assert.match(quickstart, /kb-obsidian-semantic-sync\.md/);
  assert.match(quickstart, /entities\/\*\.md/);
  assert.match(quickstart, /sources\/\*\.md/);
  assert.doesNotMatch(quickstart, /GITHUB_PACKAGES_TOKEN/);
  assert.match(quickstart, /npm\.pkg\.github\.com/);

  const obsidianGuidePath = path.resolve(process.cwd(), 'docs/operations/kb-obsidian-semantic-sync.md');
  assert.ok(existsSync(obsidianGuidePath));
  const obsidianGuide = readFileSync(obsidianGuidePath, 'utf8');
  assert.match(obsidianGuide, /Cloudflare-hosted `kb-http` remains the source of truth/);
  assert.match(obsidianGuide, /Raw `kb sync push` remains a support-mode escape hatch/);
  assert.match(obsidianGuide, /Destructive entity rewrites/);
  assert.match(obsidianGuide, /state: semantic_blocked/);
  assert.match(obsidianGuide, /kb validate-mirror --changes/);
  assert.match(obsidianGuide, /kb health --stats/);
  assert.match(obsidianGuide, /kb conflicts list/);

  const deploymentModel = readFileSync(path.resolve(process.cwd(), 'docs/product/deployment-model.md'), 'utf8');
  assert.match(deploymentModel, /agent-first/);
  assert.match(deploymentModel, /Plain local Codex \/ Claude \/ Pi \/ Cursor \/ shell agent/);
  assert.match(deploymentModel, /Remote\/serverless agent/);
  assert.match(deploymentModel, /deployed Worker `\/mcp`/);
  assert.match(deploymentModel, /does not claim to own every chat bridge/);
  assert.doesNotMatch(deploymentModel, /\btenant\b/i);

  const cloudflareGuide = readFileSync(path.resolve(process.cwd(), 'docs/cloudflare-agent-setup.md'), 'utf8');
  assert.match(cloudflareGuide, /canonical KB surface on Cloudflare/);
  assert.match(cloudflareGuide, /workspaceRole: "canonical-production"/);
  assert.match(cloudflareGuide, /workspaceRole: canonical-production/);
  assert.match(cloudflareGuide, /KB_BASE_URL/);
  assert.match(cloudflareGuide, /KB_API_TOKEN/);
  assert.match(cloudflareGuide, /kb cloudflare deploy/);
  assert.match(cloudflareGuide, /kb cloudflare verify/);
  assert.match(cloudflareGuide, /node_modules\/@emmassist-co\/kb-cli\/skills\/kb-write/);
  assert.match(cloudflareGuide, /@emmassist-co\/kb-mcp/);
  assert.match(cloudflareGuide, /kb-cloudflare-setup/);
  assert.match(cloudflareGuide, /kb-agent-improvement/);
  assert.match(cloudflareGuide, /agents own reading, reasoning, scheduling, approval, and run state/);
  assert.match(cloudflareGuide, /wrangler\.jsonc/);
  assert.match(cloudflareGuide, /streamable-http/);
  assert.match(cloudflareGuide, /## Recovery And Repair Notes/);
  assert.match(cloudflareGuide, /If an agent writes stale or incorrect memory/);

  for (const skillName of ['kb-local-setup', 'kb-write', 'kb-agent-improvement', 'kb-cloudflare-setup']) {
    const skillDir = path.resolve(process.cwd(), 'packages/kb-cli/skills', skillName);
    const skillText = readFileSync(path.join(skillDir, 'SKILL.md'), 'utf8');
    assert.match(skillText, /^---\n[\s\S]*name: /);
    assert.match(skillText, /description: /);
    assert.ok(existsSync(path.join(skillDir, 'agents/openai.yaml')));
    assert.match(skillText, /node_modules\/@emmassist-co\/kb-cli\/skills|github\.com\/emmassist-co\/kb|packages\/kb-cli\/recipes/);
  }

  assert.match(packageSkill, /kb remember --json -/);
  assert.match(packageSkill, /kb record --json @payload\.json/);
  assert.match(packageSkill, /kb relate --json @relation\.json/);
  assert.match(packageSkill, /kb annotate --json -/);
  assert.match(packageSkill, /kb validate record/);
  assert.match(packageSkill, /query-relations/);
  assert.match(packageSkill, /kb evidence --id/);
  assert.match(packageSkill, /kb recall --json/);
  assert.match(packageSkill, /kb submit-proposal --json @proposal\.json/);
  assert.match(packageSkill, /kb debt/);

  assert.equal(kbCliPackage.version, '1.12.0');
  assert.ok(kbCliPackage.files.includes('skills'));
  assert.ok(kbCliPackage.files.includes('recipes'));

  const recipeIndexPath = path.resolve(process.cwd(), 'packages/kb-cli/recipes/README.md');
  assert.ok(existsSync(recipeIndexPath));
  const recipeIndex = readFileSync(recipeIndexPath, 'utf8');
  assert.match(recipeIndex, /Agents think\. KB stores, validates, retrieves, relates, and exposes evidence\./);
  assert.match(recipeIndex, /Manual Smoke-Test Checklist/);
  assert.match(recipeIndex, /agent-maintenance-review\.md/);
  assert.match(recipeIndex, /agent-doc-review-to-kb\.md/);
  assert.match(recipeIndex, /agent-correction-sweep\.md/);
  assert.match(recipeIndex, /agent-relation-curation\.md/);
  assert.match(recipeIndex, /agent-stale-knowledge-review\.md/);
  assert.match(recipeIndex, /proposal-format\.md/);
  assert.doesNotMatch(recipeIndex, /kb-local improve/);
  assert.doesNotMatch(recipeIndex, /kb-local ingest-docs/);
  assert.doesNotMatch(recipeIndex, /kb-local detect-contradictions/);

  for (const recipeName of ['agent-maintenance-review', 'agent-doc-review-to-kb', 'agent-correction-sweep', 'agent-relation-curation', 'agent-stale-knowledge-review']) {
    const recipePath = path.resolve(process.cwd(), 'packages/kb-cli/recipes', `${recipeName}.md`);
    assert.ok(existsSync(recipePath), `${recipeName} recipe should exist`);
    const recipe = readFileSync(recipePath, 'utf8');
    assert.match(recipe, /Worked Example/);
    assert.match(recipe, /Situation/);
    assert.match(recipe, /Inspect/);
    assert.match(recipe, /Agent Judgment/);
    assert.match(recipe, /Proposed Writes/);
    assert.match(recipe, /Validation|Validate/);
    assert.match(recipe, /Verification|Verify/);
    assert.match(recipe, /Non-Goals/);
    assert.doesNotMatch(recipe, /kb-local improve/);
    assert.doesNotMatch(recipe, /kb-local ingest-docs/);
    assert.doesNotMatch(recipe, /kb-local detect-contradictions/);
  }

  const proposalFormat = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/recipes/proposal-format.md'), 'utf8');
  assert.match(proposalFormat, /kb validate remember/);
  assert.match(proposalFormat, /kb validate record/);
  assert.match(proposalFormat, /kb validate relate/);
  assert.match(proposalFormat, /kb validate annotate/);
  assert.match(proposalFormat, /kb submit-proposal --json @proposal\.json/);
  assert.match(proposalFormat, /kb review-proposal --id/);
  assert.match(proposalFormat, /kb apply-proposal --id/);
  assert.match(proposalFormat, /does not author proposals, decide truth, schedule review, or arbitrate disagreements by itself/);

  const migrationStatus = readFileSync(path.resolve(process.cwd(), 'docs/migration-status.md'), 'utf8');
  assert.match(migrationStatus, /## Staged Public Package Set/);
  assert.match(migrationStatus, /@emmassist-co\/kb-core/);
  assert.match(migrationStatus, /@emmassist-co\/kb-mcp/);
  assert.match(migrationStatus, /@emmassist-co\/kb-flue-adapter/);
  assert.match(migrationStatus, /@emmassist-co\/kb-autoresearch/);
});
