import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';

test('kb docs describe the staged public package set and current consumer entry point', () => {
  const repoReadme = readFileSync(path.resolve(process.cwd(), 'README.md'), 'utf8');
  assert.match(repoReadme, /## Public Package Set/);
  assert.match(repoReadme, /@emmassist-co\/kb-core/);
  assert.match(repoReadme, /@emmassist-co\/kb-storage-file/);
  assert.match(repoReadme, /@emmassist-co\/kb-storage-cloudflare/);
  assert.match(repoReadme, /@emmassist-co\/kb-http/);
  assert.match(repoReadme, /@emmassist-co\/kb-mcp/);
  assert.match(repoReadme, /@emmassist-co\/kb-cli/);
  assert.match(repoReadme, /Not yet in the staged public package set/);
  assert.match(repoReadme, /@emmassist-co\/kb-flue-adapter/);
  assert.match(repoReadme, /@emmassist-co\/kb-autoresearch/);
  assert.match(repoReadme, /## Benchmark Standard/);
  assert.match(repoReadme, /admin-world-v3/);
  assert.match(repoReadme, /gbrain-world/);
  assert.match(repoReadme, /exact public GBrain GitHub benchmark contract: `145` queries across attendance, employment, investing, and advising/);
  assert.match(repoReadme, /core-six/);
  assert.match(repoReadme, /\| `core-six` \| deterministic floor \| `72 retrieval \+ 28 non-retrieval` \| `30\.0%` \| `94\.4%` \| `93\.1%` \| `88\.4%` \| `pass` \|/);
  assert.match(repoReadme, /\| `admin-world-v3 dev` \| product-core optimize rail \| `216 queries` \| `41\.5%` \| `99\.3%` \| `98\.7%` \| `92\.6%` \| `floor reached` \|/);
  assert.match(repoReadme, /\| `admin-world-v3 holdout` \| product-core confirm rail \| `72 queries` \| `41\.7%` \| `99\.3%` \| `100\.0%` \| `93\.6%` \| `floor reached` \|/);
  assert.match(repoReadme, /\| `gbrain-world` \| exact public external rail \| `145 queries` \| `35\.6%` \| `99\.3%` \| `100\.0%` \| `99\.5%` \| `guardrails passed` \|/);
  assert.match(repoReadme, /GBrain` public headline used in the side-by-side runner/);
  assert.match(repoReadme, /288 retrieval queries/);
  assert.match(repoReadme, /72 holdout queries/);
  assert.match(repoReadme, /kb-scorecard-latest\.md/);
  assert.match(repoReadme, /P@5 35\.6%/);
  assert.match(repoReadme, /R@5 99\.3%/);
  assert.match(repoReadme, /optimize on `admin-world-v3 dev`/);
  assert.match(repoReadme, /confirm on `admin-world-v3 holdout`/);
  assert.match(repoReadme, /block regressions on `core-six dev` and `core-six holdout`/);
  assert.match(repoReadme, /external reference rail/);
  assert.match(repoReadme, /after any major KB change, rerun the benchmark rails and refresh the published benchmark snapshot/);

  const packageSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-write/SKILL.md'), 'utf8');
  assert.match(packageSkill, /github\.com\/emmassist-co\/kb/);

  const setupSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-local-setup/SKILL.md'), 'utf8');
  assert.doesNotMatch(setupSkill, /GITHUB_PACKAGES_TOKEN/);
  assert.match(setupSkill, /KB_ROOT_DIR/);
  assert.match(setupSkill, /KB_TENANT_ID/);
  assert.match(setupSkill, /npx kb-local inspect/);
  assert.ok(existsSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-local-setup/agents/openai.yaml')));

  const cloudflareSetupSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-cloudflare-setup/SKILL.md'), 'utf8');
  assert.match(cloudflareSetupSkill, /canonical Cloudflare-hosted KB surface/);
  assert.match(cloudflareSetupSkill, /canonical-production/);
  assert.match(cloudflareSetupSkill, /KB_BASE_URL/);
  assert.match(cloudflareSetupSkill, /KB_API_TOKEN/);
  assert.match(cloudflareSetupSkill, /kb-local cloudflare deploy/);
  assert.match(cloudflareSetupSkill, /kb-local cloudflare verify/);
  assert.match(cloudflareSetupSkill, /docs\/cloudflare-agent-setup\.md/);
  assert.ok(existsSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-cloudflare-setup/agents/openai.yaml')));

  const readme = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/README.md'), 'utf8');
  assert.match(readme, /npm install @emmassist-co\/kb-cli/);
  assert.match(readme, /npx kb-local inspect/);
  assert.match(readme, /kb-local-setup/);
  assert.match(readme, /cloudflare-agent-setup\.md/);
  assert.match(readme, /kb-cloudflare-setup/);
  assert.match(readme, /KB_API_TOKEN/);
  assert.match(readme, /kb-local cloudflare deploy/);
  assert.match(readme, /kb-local cloudflare verify/);
  assert.doesNotMatch(readme, /npm\.pkg\.github\.com/);

  const mcpReadme = readFileSync(path.resolve(process.cwd(), 'packages/kb-mcp/README.md'), 'utf8');
  assert.match(mcpReadme, /MCP transport adapter/);
  assert.match(mcpReadme, /Install/);
  assert.match(mcpReadme, /Tool Surface/);
  assert.match(mcpReadme, /npm run smoke:kb-mcp/);
  assert.match(mcpReadme, /shared-secret bearer auth/);
  assert.match(mcpReadme, /streamable-http/);
  assert.match(mcpReadme, /Authorization/);

  const quickstart = readFileSync(path.resolve(process.cwd(), 'docs/consumer-quickstart.md'), 'utf8');
  assert.match(quickstart, /public npm registry/);
  assert.match(quickstart, /cloudflare-agent-setup\.md/);
  assert.match(quickstart, /KB_TENANT_ID/);
  assert.match(quickstart, /KB_ROOT_DIR/);
  assert.match(quickstart, /npm install @emmassist-co\/kb-cli/);
  assert.match(quickstart, /npx kb-local sync status/);
  assert.match(quickstart, /support and debugging path/);
  assert.match(quickstart, /npx skills add https:\/\/github\.com\/emmassist-co\/kb\/tree\/main\/packages\/kb-cli\/skills\/kb-local-setup/);
  assert.match(quickstart, /npx skills add https:\/\/github\.com\/emmassist-co\/kb\/tree\/main\/packages\/kb-cli\/skills\/kb-cloudflare-setup/);
  assert.match(quickstart, /canonical Cloudflare KB surface/);
  assert.match(quickstart, /KB_API_TOKEN/);
  assert.match(quickstart, /kb-local cloudflare deploy/);
  assert.match(quickstart, /kb-local cloudflare verify/);
  assert.match(quickstart, /streamable-http/);
  assert.doesNotMatch(quickstart, /GITHUB_PACKAGES_TOKEN/);
  assert.doesNotMatch(quickstart, /npm\.pkg\.github\.com/);

  const cloudflareGuide = readFileSync(path.resolve(process.cwd(), 'docs/cloudflare-agent-setup.md'), 'utf8');
  assert.match(cloudflareGuide, /canonical KB surface on Cloudflare/);
  assert.match(cloudflareGuide, /workspaceRole: "canonical-production"/);
  assert.match(cloudflareGuide, /workspaceRole: canonical-production/);
  assert.match(cloudflareGuide, /KB_BASE_URL/);
  assert.match(cloudflareGuide, /KB_API_TOKEN/);
  assert.match(cloudflareGuide, /kb-local cloudflare deploy/);
  assert.match(cloudflareGuide, /kb-local cloudflare verify/);
  assert.match(cloudflareGuide, /@emmassist-co\/kb-mcp/);
  assert.match(cloudflareGuide, /kb-cloudflare-setup/);
  assert.match(cloudflareGuide, /wrangler\.jsonc/);
  assert.match(cloudflareGuide, /streamable-http/);

  const migrationStatus = readFileSync(path.resolve(process.cwd(), 'docs/migration-status.md'), 'utf8');
  assert.match(migrationStatus, /## Staged Public Package Set/);
  assert.match(migrationStatus, /@emmassist-co\/kb-core/);
  assert.match(migrationStatus, /@emmassist-co\/kb-mcp/);
  assert.match(migrationStatus, /@emmassist-co\/kb-flue-adapter/);
  assert.match(migrationStatus, /@emmassist-co\/kb-autoresearch/);
});
