import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';

test('kb docs describe the staged public package set and current consumer entry point', () => {
  const repoReadme = readFileSync(path.resolve(process.cwd(), 'README.md'), 'utf8');
  assert.match(repoReadme, /## Public Package Set/);
  assert.match(repoReadme, /@emmassist-co\/kb-core/);
  assert.match(repoReadme, /@emmassist-co\/kb-storage-file/);
  assert.match(repoReadme, /@emmassist-co\/kb-storage-cloudflare/);
  assert.match(repoReadme, /@emmassist-co\/kb-http/);
  assert.match(repoReadme, /@emmassist-co\/kb-mcp/);
  assert.match(repoReadme, /@emmassist-co\/kb-cli/);
  assert.match(repoReadme, /Not yet in the staged public package set/);
  assert.match(repoReadme, /@emmassist-co\/kb-flue-adapter/);
  assert.match(repoReadme, /@emmassist-co\/kb-autoresearch/);
  assert.match(repoReadme, /## Benchmark Standard/);
  assert.match(repoReadme, /admin-world-v3/);
  assert.match(repoReadme, /gbrain-evals-upstream/);
  assert.match(repoReadme, /gbrain-world/);
  assert.match(repoReadme, /literal upstream `gbrain-evals` harness run side-by-side against real `gbrain` and our KB on the public `world-v1` benchmark/);
  assert.match(repoReadme, /core-six/);
  assert.match(repoReadme, /Fixed P@5/);
  assert.match(repoReadme, /Returned P@5/);
  assert.match(repoReadme, /Fixed ceiling/);
  assert.match(repoReadme, /\| `core-six` \| deterministic floor \| `72 retrieval \+ 28 non-retrieval` \| `30\.6%` \| `33\.8%` \| `31\.7%` \| `96\.5%` \| `89\.7%` \| `87\.3%` \| `pass` \|/);
  assert.match(repoReadme, /\| `admin-world-v3 dev` \| product-core optimize rail \| `216 queries` \| `40\.0%` \| `90\.3%` \| `42\.0%` \| `95\.6%` \| `98\.7%` \| `91\.4%` \| `floor reached` \|/);
  assert.match(repoReadme, /\| `admin-world-v3 holdout` \| product-core confirm rail \| `72 queries` \| `40\.6%` \| `90\.9%` \| `42\.2%` \| `96\.5%` \| `100\.0%` \| `93\.0%` \| `floor reached` \|/);
  assert.match(repoReadme, /\| `gbrain-evals-upstream` \| strict public external rail \| `145 queries` \| `n\/a` \| `76\.6%` \| `n\/a` \| `99\.5%` \| `n\/a` \| `n\/a` \| `real gbrain side-by-side` \|/);
  assert.match(repoReadme, /\| `gbrain-world` \| local diagnostic rail \| `145 queries` \| `36\.0%` \| `76\.7%` \| `36\.0%` \| `100\.0%` \| `100\.0%` \| `100\.0%` \| `diagnostic only` \|/);
  assert.match(repoReadme, /\| `relation-paraphrase-v1` \| anti-cheat paraphrase rail \| `4 queries` \| `45\.0%` \| `87\.5%` \| `45\.0%` \| `100\.0%` \| `100\.0%` \| `100\.0%` \| `guardrail pass` \|/);
  assert.match(repoReadme, /\| `relation-transfer-v1` \| prose-only transfer rail \| `4 queries` \| `20\.0%` \| `87\.5%` \| `20\.0%` \| `100\.0%` \| `100\.0%` \| `100\.0%` \| `guardrail pass` \|/);
  assert.match(repoReadme, /external reference rail/);
  assert.match(repoReadme, /relation-paraphrase-v1/);
  assert.match(repoReadme, /relation-transfer-v1/);
  assert.match(repoReadme, /check:kb:anti-cheat/);
  assert.match(repoReadme, /before describing the GBrain posture as evidence of product-general relation quality/);
  assert.match(repoReadme, /after any major KB change, rerun the benchmark rails and refresh the published benchmark snapshot/);

  const benchmarkDocs = readFileSync(path.resolve(process.cwd(), 'docs/operations/kb-benchmark.md'), 'utf8');
  assert.match(benchmarkDocs, /npm run check:kb:anti-cheat/);
  assert.match(benchmarkDocs, /npm run eval:kb:relation-paraphrase/);
  assert.match(benchmarkDocs, /npm run eval:kb:relation-transfer/);
  assert.match(benchmarkDocs, /Do not describe GBrain results as product-general relation quality unless these guardrails pass too/);
  assert.match(benchmarkDocs, /official GBrain GitHub README headline/);
  assert.match(benchmarkDocs, /same `240` page corpus, the same `145` public queries/);
  assert.match(benchmarkDocs, /Runtime\/package code is guarded against GBrain-specific markers/);

  assert.match(repoReadme, /288 retrieval queries/);
  assert.match(repoReadme, /72 holdout queries/);
  assert.match(repoReadme, /kb-scorecard-latest\.md/);
  assert.match(repoReadme, /GBrain` official GitHub README headline/);
  assert.match(repoReadme, /same upstream `gbrain-evals` runner, the same `240` page corpus, the same `145` public queries/);
  assert.match(repoReadme, /benchmark-metadata-blind/);
  assert.match(repoReadme, /not a claim that KB is broadly better than GBrain across synthesis, ingestion, vector\/reranker search, or every memory workflow/);
  assert.match(repoReadme, /gbrain returned-denominator P@5 49\.1%, R@5 97\.9%/);
  assert.match(repoReadme, /kb-upstream returned-denominator P@5 76\.6%, R@5 99\.5%/);
  assert.match(repoReadme, /optimize on `admin-world-v3 dev`/);
  assert.match(repoReadme, /confirm on `admin-world-v3 holdout`/);
  assert.match(repoReadme, /block regressions on `core-six dev` and `core-six holdout`/);
  assert.match(repoReadme, /external reference rail/);
  assert.match(repoReadme, /after any major KB change, rerun the benchmark rails and refresh the published benchmark snapshot/);

  const packageSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-write/SKILL.md'), 'utf8');
  assert.match(packageSkill, /github\.com\/emmassist-co\/kb/);

  const setupSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-local-setup/SKILL.md'), 'utf8');
  assert.doesNotMatch(setupSkill, /GITHUB_PACKAGES_TOKEN/);
  assert.match(setupSkill, /KB_ROOT_DIR/);
  assert.match(setupSkill, /KB_TENANT_ID/);
  assert.match(setupSkill, /npx kb-local inspect/);
  assert.ok(existsSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-local-setup/agents/openai.yaml')));

  const cloudflareSetupSkill = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-cloudflare-setup/SKILL.md'), 'utf8');
  assert.match(cloudflareSetupSkill, /canonical Cloudflare-hosted KB surface/);
  assert.match(cloudflareSetupSkill, /canonical-production/);
  assert.match(cloudflareSetupSkill, /KB_BASE_URL/);
  assert.match(cloudflareSetupSkill, /KB_API_TOKEN/);
  assert.match(cloudflareSetupSkill, /kb-local cloudflare deploy/);
  assert.match(cloudflareSetupSkill, /kb-local cloudflare verify/);
  assert.match(cloudflareSetupSkill, /docs\/cloudflare-agent-setup\.md/);
  assert.ok(existsSync(path.resolve(process.cwd(), 'packages/kb-cli/skills/kb-cloudflare-setup/agents/openai.yaml')));

  const readme = readFileSync(path.resolve(process.cwd(), 'packages/kb-cli/README.md'), 'utf8');
  assert.match(readme, /npm install @emmassist-co\/kb-cli/);
  assert.match(readme, /npx kb-local inspect/);
  assert.match(readme, /kb-local-setup/);
  assert.match(readme, /cloudflare-agent-setup\.md/);
  assert.match(readme, /kb-cloudflare-setup/);
  assert.match(readme, /KB_API_TOKEN/);
  assert.match(readme, /kb-local cloudflare deploy/);
  assert.match(readme, /kb-local cloudflare verify/);
  assert.match(readme, /kb-local validate-mirror --changes/);
  assert.match(readme, /kb-local health --stats/);
  assert.match(readme, /kb-local conflicts list/);
  assert.doesNotMatch(readme, /npm\.pkg\.github\.com/);

  const mcpReadme = readFileSync(path.resolve(process.cwd(), 'packages/kb-mcp/README.md'), 'utf8');
  assert.match(mcpReadme, /MCP transport adapter/);
  assert.match(mcpReadme, /Install/);
  assert.match(mcpReadme, /Tool Surface/);
  assert.match(mcpReadme, /npm run smoke:kb-mcp/);
  assert.match(mcpReadme, /shared-secret bearer auth/);
  assert.match(mcpReadme, /streamable-http/);
  assert.match(mcpReadme, /Authorization/);

  const quickstart = readFileSync(path.resolve(process.cwd(), 'docs/consumer-quickstart.md'), 'utf8');
  assert.match(quickstart, /public npm registry/);
  assert.match(quickstart, /cloudflare-agent-setup\.md/);
  assert.match(quickstart, /KB_TENANT_ID/);
  assert.match(quickstart, /KB_ROOT_DIR/);
  assert.match(quickstart, /npm install @emmassist-co\/kb-cli/);
  assert.match(quickstart, /npx kb-local sync status/);
  assert.match(quickstart, /npx kb-local validate-mirror/);
  assert.match(quickstart, /npx kb-local health/);
  assert.match(quickstart, /support and debugging path/);
  assert.match(quickstart, /npx skills add https:\/\/github\.com\/emmassist-co\/kb\/tree\/main\/packages\/kb-cli\/skills\/kb-local-setup/);
  assert.match(quickstart, /npx skills add https:\/\/github\.com\/emmassist-co\/kb\/tree\/main\/packages\/kb-cli\/skills\/kb-cloudflare-setup/);
  assert.match(quickstart, /canonical Cloudflare KB surface/);
  assert.match(quickstart, /KB_API_TOKEN/);
  assert.match(quickstart, /kb-local cloudflare deploy/);
  assert.match(quickstart, /kb-local cloudflare verify/);
  assert.match(quickstart, /streamable-http/);
  assert.match(quickstart, /kb-obsidian-semantic-sync\.md/);
  assert.match(quickstart, /entities\/\*\.md/);
  assert.match(quickstart, /sources\/\*\.md/);
  assert.doesNotMatch(quickstart, /GITHUB_PACKAGES_TOKEN/);
  assert.doesNotMatch(quickstart, /npm\.pkg\.github\.com/);

  const obsidianGuidePath = path.resolve(process.cwd(), 'docs/operations/kb-obsidian-semantic-sync.md');
  assert.ok(existsSync(obsidianGuidePath));
  const obsidianGuide = readFileSync(obsidianGuidePath, 'utf8');
  assert.match(obsidianGuide, /Cloudflare-hosted `kb-http` remains the source of truth/);
  assert.match(obsidianGuide, /Raw `kb sync push` remains a support-mode escape hatch/);
  assert.match(obsidianGuide, /Destructive entity rewrites/);
  assert.match(obsidianGuide, /state: semantic_blocked/);
  assert.match(obsidianGuide, /kb validate-mirror --changes/);
  assert.match(obsidianGuide, /kb health --stats/);
  assert.match(obsidianGuide, /kb conflicts list/);

  const cloudflareGuide = readFileSync(path.resolve(process.cwd(), 'docs/cloudflare-agent-setup.md'), 'utf8');
  assert.match(cloudflareGuide, /canonical KB surface on Cloudflare/);
  assert.match(cloudflareGuide, /workspaceRole: "canonical-production"/);
  assert.match(cloudflareGuide, /workspaceRole: canonical-production/);
  assert.match(cloudflareGuide, /KB_BASE_URL/);
  assert.match(cloudflareGuide, /KB_API_TOKEN/);
  assert.match(cloudflareGuide, /kb-local cloudflare deploy/);
  assert.match(cloudflareGuide, /kb-local cloudflare verify/);
  assert.match(cloudflareGuide, /@emmassist-co\/kb-mcp/);
  assert.match(cloudflareGuide, /kb-cloudflare-setup/);
  assert.match(cloudflareGuide, /wrangler\.jsonc/);
  assert.match(cloudflareGuide, /streamable-http/);

  const migrationStatus = readFileSync(path.resolve(process.cwd(), 'docs/migration-status.md'), 'utf8');
  assert.match(migrationStatus, /## Staged Public Package Set/);
  assert.match(migrationStatus, /@emmassist-co\/kb-core/);
  assert.match(migrationStatus, /@emmassist-co\/kb-mcp/);
  assert.match(migrationStatus, /@emmassist-co\/kb-flue-adapter/);
  assert.match(migrationStatus, /@emmassist-co\/kb-autoresearch/);
});
